#version: "3.9"
services:
  test-tunnel-net:
    image: test-tunnel-net:0.1.0
    container_name: test-tunnel-net
    restart: unless-stopped
    user: ":"
    networks:
      - tunnel-net #the name of our Cloudflare Zero Trust Tunnel Docker's Network
    ports:
      - 8456:8456

networks:
  tunnel-net: #this is the name of the network that we created in the Cloudflared Container
    external: true #we already created it!
